using MtgEngine.Common.Mana;

namespace MtgEngine.Common.Enums
{
    /// <summary>
    /// All types of mana that can appear in Mana Costs. The only colors that can be generated by lands are White, Blue, Black, Red, Green, and Colorless
    /// </summary>
    public enum ManaColor
    {
        // Normal Mana Types

        [Mana("{W}")]
        White,          // Must be paid with White mana sources

        [Mana("{U}")]
        Blue,           // Must be paid with Blue mana sources

        [Mana("{B}")]
        Black,          // Must be paid with Black mana sources

        [Mana("{R}")]
        Red,            // Must be paid with Red mana sources

        [Mana("{G}")]
        Green,          // Must be paid with Green mana sources

        [Mana("{C}")]
        Colorless,      // Must be paid with Colorless mana sources, cannot be generated from "Any Color" mana sources

        // Generic gets no attribute because it appears differently in Mana Costs depending on the amount
        Generic,        // May be paid with any mana source, cannot be explicitly generated

        [Mana("{X}", 0)]
        GenericX,       // Same as Generic, but the amount is determined at the time the mana cost is to be paid. Cannot be explicitly generated

        // Phyrexian Mana Types

        [Mana("{W/P}")]
        PhyrexianWhite, // May be paid with White mana sources or 2 life, cannot be explicitly generated

        [Mana("{U/P}")]
        PhyrexianBlue,  // May be paid with Blue mana sources or 2 life, cannot be explicitly generated

        [Mana("{B/P}")]
        PhyrexianBlack, // May be paid with Black mana sources or 2 life, cannot be explicitly generated

        [Mana("{R/P}")]
        PhyrexianRed,   // May be paid with Red mana sources or 2 life, cannot be explicitly generated

        [Mana("{G/P}")]
        PhyrexianGreen, // May be paid with Green mana sources or 2 life, cannot be explicitly generated

        // 2 Color Hybrid Mana Types

        [Mana("{W/U}")]
        WhiteBlue,      // May be paid with White or Blue mana sources, cannot be explicitly generated

        [Mana("{W/B}")]
        WhiteBlack,     // May be paid with White or Black mana sources, cannot be explicitly generated

        [Mana("{U/B}")]
        BlueBlack,      // May be paid with Blue or Black mana sources, cannot be explicitly generated

        [Mana("{U/R}")]
        BlueRed,        // May be paid with Blue or Red mana sources, cannot be explicitly generated

        [Mana("{B/R}")]
        BlackRed,       // May be paid with Black or Red mana sources, cannot be explicitly generated

        [Mana("{B/G}")]
        BlackGreen,     // May be paid with Black or Green mana sources, cannot be explicitly generated

        [Mana("{R/G}")]
        RedGreen,       // May be paid with Red or Green mana sources, cannot be explicitly generated

        [Mana("{R/W}")]
        RedWhite,       // May be paid with Red or White mana sources, cannot be explicitly generated

        [Mana("{G/W}")]
        GreenWhite,     // May be paid with Green or White mana sources, cannot be explicitly generated

        [Mana("{G/U}")]
        GreenBlue,      // May be paid with Green or Blue mana sources, cannot be explicitly generated

        // 1 Color Hybrid Mana Types

        [Mana("{2/W}", 2)]
        TwoOrWhite,     // May be paid with White mana sources or 2 mana sources of any other color, cannot be explicitly generated

        [Mana("{2/U}", 2)]
        TwoOrBlue,      // May be paid with Blue mana sources or 2 mana sources of any other color, cannot be explicitly generated

        [Mana("{2/B}", 2)]
        TwoOrBlack,     // May be paid with Black mana sources or 2 mana sources of any other color, cannot be explicitly generated

        [Mana("{2/R}", 2)]
        TwoOrRed,       // May be paid with Red mana sources or 2 mana sources of any other color, cannot be explicitly generated

        [Mana("{2/G}", 2)]
        TwoOrGreen      // May be paid with Green mana sources or 2 mana sources of any other color, cannot be explicitly generated
    }
}
