namespace MtgEngine.Common.Enums
{
    public enum StaticAbility
    {
        Flying,
        Reach,
        Haste,
        Deathtouch,
        Defender,
        Indestructible,
        Fear,
        FirstStrike,
        DoubleStrike,
        Vigilance,
        Unblockable,
        Devoid,
        Shadow,
        Horsemanship,
        Plainswalk,
        Islandwalk,
        Swampwalk,
        Mountainwalk,
        Forestwalk,
        Flash,
        Shroud,
        Hexproof,
        Trample,
        Infect
    }
}
